### ISSUE TITLE
自建服务器，在网页测试发送消息没问题

### ISSUE THREAD

**Issue by liesauer** [yafoo/pushme-server#1]
但是在App上面自带的测试一直发送失败

**Comment by yafoo** [comment]
> 但是在App上面自带的测试一直发送失败

在自建的网页端发送成功了没？如果成功了就没啥问题。

app端，发送测试消息那里，需要设置你的接口地址，前面带http，不是80端口的话后面带端口号，然后在输入框编写消息，点击发送，发送一次后会保存接口地址，然后下面的demo按钮就也可以用了

这个地方的逻辑有点不美

**Comment by liesauer** [comment]
> > 但是在App上面自带的测试一直发送失败
> 
> 在自建的网页端发送成功了没？如果成功了就没啥问题。
> 
> app端，发送测试消息那里，需要设置你的接口地址，前面带http，不是80端口的话后面带端口号，然后在输入框编写消息，点击发送，发送一次后会保存接口地址，然后下面的demo按钮就也可以用了
> 
> 这个地方的逻辑有点不美

网页是没问题的，我App上面的地址也是没问题的，但是App就发送失败
![image](https://github.com/yafoo/pushme-server/assets/8676741/a3355e5f-bfb3-405e-a8e6-584313f3a2ed)

**Comment by yafoo** [comment]
标题 内容填写一下，发送一次试试，如果还不行，可能程序有问题，我明天看看。

**Comment by liesauer** [comment]
> 标题 内容填写一下，发送一次试试，如果还不行，可能程序有问题，我明天看看。

都试过了，也是失败

**Comment by yafoo** [comment]
> > 标题 内容填写一下，发送一次试试，如果还不行，可能程序有问题，我明天看看。
> 
> 都试过了，也是失败

好的，我明天看看程序，可能程序有问题

**Comment by yafoo** [comment]
问题已经解决，你下载最新版（v2.0.1）试试

**Comment by liesauer** [comment]
测试没问题了
