### ISSUE TITLE
自建服务域名连接问题

### ISSUE THREAD

**Issue by imaxhung** [yafoo/pushme-server#2]
你好
本机node ./server.js启动后，3100端口通过caddy反代到https://example.com，3010本机web正常访问并同步设置安卓push_key
安卓端自建服务那边怎么填呢
https://exsample.com+443，直接报错
example.com+443，报ConnectFailed

**Comment by yafoo** [comment]
3100端口运行的是mqtt协议，不是http。反代的话，要反代tcp流量。这一块我还没弄过，你试试看

**Comment by imaxhung** [comment]
好明白

**Comment by yafoo** [comment]
另外客户端连接用的mqtt，不是mqtts，你都试试吧。

百度搜索nginx反代mqtt，可以找到一些介绍文章。

**Comment by imaxhung** [comment]
好的谢谢
