### ISSUE TITLE
请求加入ipv6支持

### ISSUE THREAD

**Issue by AnxysUaen** [yafoo/pushme-server#3]
局域网测试 通过ipv6地址向server发送请求失败，ipv4正常

**Comment by yafoo** [comment]
好的，我研究一下

**Comment by yafoo** [comment]
ipv6已支持，请docker拉取最新镜像，或下载最新源码，PushMe APP和PushMeClient最好也更新到最新版。

**Comment by AnxysUaen** [comment]
> ipv6已支持，请docker拉取最新镜像，或下载最新源码，PushMe APP和PushMeClient最好也更新到最新版。

感谢大佬，神速啊
